package client.data;

import client.utils.ErrorCtrl;
import com.google.inject.Inject;
import javafx.application.Platform;
import org.jspecify.annotations.NonNull;
import org.springframework.messaging.converter.JacksonJsonMessageConverter;
import org.springframework.messaging.simp.stomp.*;
import org.springframework.web.socket.client.standard.StandardWebSocketClient;
import org.springframework.web.socket.messaging.WebSocketStompClient;

import java.lang.reflect.Type;
import java.util.Arrays;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.function.Consumer;

public class WebSocketManager {

    private final int subscriptionTime = 10;
    private ErrorCtrl errorCtrl;
    private StompSession session;
    private final CountDownLatch connectionLatch = new CountDownLatch(1);
    private final String url = "ws://localhost:8080/autoupdates-websocket";

    @Inject
    private WebSocketManager(ErrorCtrl errors){
        connect();
        this.errorCtrl = errors;
    }

    // /!\ WARNING /!\ THE DOCUMENTATION USED TO WRITE THE FOLLOWING CODE WAS VERY LIMITED. I KINDA KNOW WHAT THIS DOES.
    // AI WAS ALSO USED TO SUMMARIZE DOCUMENTATION AND GENERATE EXAMPLES
    // THIS CODE IS A TICKING TIME BOMB AND MUST BE THOROUGHLY CHECKED AND TESTED

    /**
     * Subscribes to a websocket update topic and returns the subscription object
     * @param <T> The type of updatePackets we're managing
     * @param topic The socket path
     * @param type The Class type to convert from JSON into
     * @param onMessage The callback function to run when data arrives
     * @return The subscription object generated by the desired websocket subscription
     */
    public <T> StompSession.Subscription subscribe(String topic, Class<T> type, Consumer<T> onMessage) {
        try {
            // Wait up to 10 seconds for the connection to finish
            if (connectionLatch.await(subscriptionTime, TimeUnit.SECONDS)) {
                return session.subscribe(topic, new StompFrameHandler() {
                    @Override
                    public Type getPayloadType(@NonNull StompHeaders headers) {
                        return type;
                    }

                    @Override
                    public void handleFrame(@NonNull StompHeaders headers, Object payload) {
                        Platform.runLater(() -> onMessage.accept(type.cast(payload)));
                    }
                });
            }
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
        Platform.runLater(() -> {
            errorCtrl.showGenericError("Failed to subscribe: Connection timed out.");
        });
        return null;
    }

    private void connect() {
        WebSocketStompClient stompClient = new WebSocketStompClient(new StandardWebSocketClient());
        stompClient.setMessageConverter(new JacksonJsonMessageConverter());

        stompClient.connectAsync(url,new StompSessionHandlerAdapter() {
            @Override
            public void afterConnected(@NonNull StompSession sesh, @NonNull StompHeaders headers) {
                session = sesh;
                System.out.println("Socket Connection Established!");
            }

            @Override
            public void handleException(@NonNull StompSession sesh, StompCommand command,
                                        @NonNull StompHeaders headers, byte @NonNull [] p, @NonNull Throwable t) {
                errorCtrl.showGenericError(Arrays.toString(t.getStackTrace()));
            }

            @Override
            public void handleTransportError(StompSession sesh, Throwable e) {
                System.out.println("Connection lost. Retrying in 5 seconds...");
                // Schedule a reconnect
                Executors.newSingleThreadScheduledExecutor()
                        .schedule(() -> connect(), subscriptionTime/2, TimeUnit.SECONDS);
            }
        });
    }
}
